console.log(Math.floor(Math.random() * 11))
console.log(Math.floor(Math.random() * 11))
console.log(Math.floor(Math.random() * 11))
console.log(Math.floor(Math.random() * 11))
console.log(Math.floor(Math.random() * 11))
console.log(Math.floor(Math.random() * 11))
console.log(Math.floor(Math.random() * 11))
